//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyScheduleExample.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeeklyScheduleExample.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks.
        /// </summary>
        public static string BreaksTitle {
            get {
                return ResourceManager.GetString("BreaksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Friday.
        /// </summary>
        public static string BreaksTitleFriday {
            get {
                return ResourceManager.GetString("BreaksTitleFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Monday.
        /// </summary>
        public static string BreaksTitleMonday {
            get {
                return ResourceManager.GetString("BreaksTitleMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Saturday.
        /// </summary>
        public static string BreaksTitleSaturday {
            get {
                return ResourceManager.GetString("BreaksTitleSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Sunday.
        /// </summary>
        public static string BreaksTitleSunday {
            get {
                return ResourceManager.GetString("BreaksTitleSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Thursday.
        /// </summary>
        public static string BreaksTitleThursday {
            get {
                return ResourceManager.GetString("BreaksTitleThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Tuesday.
        /// </summary>
        public static string BreaksTitleTuesday {
            get {
                return ResourceManager.GetString("BreaksTitleTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks for Wednesday.
        /// </summary>
        public static string BreaksTitleWednesday {
            get {
                return ResourceManager.GetString("BreaksTitleWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string CultureInfo {
            get {
                return ResourceManager.GetString("CultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day off.
        /// </summary>
        public static string DayOffITitle {
            get {
                return ResourceManager.GetString("DayOffITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of a week.
        /// </summary>
        public static string DayOfWeekTitle {
            get {
                return ResourceManager.GetString("DayOfWeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break can&apos;t be added for the working type {0}.
        /// </summary>
        public static string E_BreakCanNotBeAddedForTypeWithParam {
            get {
                return ResourceManager.GetString("E_BreakCanNotBeAddedForTypeWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} can&apos;t be empty.
        /// </summary>
        public static string E_ElementCanNotBeEmptyWithParam {
            get {
                return ResourceManager.GetString("E_ElementCanNotBeEmptyWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set up the time.
        /// </summary>
        public static string E_EmptyTime {
            get {
                return ResourceManager.GetString("E_EmptyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid interval.
        /// </summary>
        public static string E_IntervalIsNotValid {
            get {
                return ResourceManager.GetString("E_IntervalIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined working type.
        /// </summary>
        public static string E_UndefinedWorkingType {
            get {
                return ResourceManager.GetString("E_UndefinedWorkingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected xml element {0}.
        /// </summary>
        public static string E_UnexpectedXmlElementWithParam {
            get {
                return ResourceManager.GetString("E_UnexpectedXmlElementWithParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working type is already set to {0}. It can&apos;t be redefined to {1}.
        /// </summary>
        public static string E_WorkingTypeMustBeNoneWithParams2 {
            get {
                return ResourceManager.GetString("E_WorkingTypeMustBeNoneWithParams2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string FromTitle {
            get {
                return ResourceManager.GetString("FromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round the clock.
        /// </summary>
        public static string RoundTheClockTitle {
            get {
                return ResourceManager.GetString("RoundTheClockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string ToTitle {
            get {
                return ResourceManager.GetString("ToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working time.
        /// </summary>
        public static string WorkingTimeTitle {
            get {
                return ResourceManager.GetString("WorkingTimeTitle", resourceCulture);
            }
        }
    }
}
